### ISSUE TITLE
proxy package

### ISSUE THREAD

**Issue by yxngl** [bzhanglab/sumer#1]
**Imports** field in the DESCRIPTION file misses _proxy_ package. It is not annotated with roxygen2. And because _proxy_ package is only available for R >= 3.4, it is necessary to update SUMER to be dependent on R >= 3.4 as well.

I wrote a few lines to calculate Jaccard index, but considering future support for other distance measurements, the dependence may be good.

**Comment by zhiaos** [comment]
this is fixed
