### ISSUE TITLE
Jaccard Similarity vs Overlap Coefficient

### ISSUE THREAD

**Issue by maciejmotyka** [bzhanglab/sumer#4]
Hi,
I've noticed that you have switched from Jaccard Similarity to Overlap Coefficient as the default similarity measure between the gene sets. Could you please explain your reasoning behind this change?

My intuition tells me that this will counteract a tendency of big, broad sets to be clustered together and instead recruit smaller sets that have a significant overlap with the bigger set, which seems like a good change.
On the other hand, it seems to behave "undesirably" in a particular situation: let set A share 30 of 40 genes with set B which has 50 genes and let set C share 31 of 40 genes with set D which has 200 genes. Overlap Coefficient will judge sets C and D to be more similar than A and B, which seems "against common sense".

I'm asking solely out of curiosity. I trust your judgment in this matter, but I have no training in the set theory so it's not obvious for me why the OC makes more sense than JS. I have an unpublished analysis including Sumer and I wonder if I should redo it using OC.

Thanks!

**Comment by zhiaos** [comment]
The new release provides the option of setting similarity metric in the config file. The default is now "Jaccard".
