### ISSUE TITLE
sumer Error: Error in abs(geneset_info[[cur.set.name]])

### ISSUE THREAD

**Issue by ederisoud** [bzhanglab/sumer#5]
Hello

Thank you for this package, it seems wonderful... but I get an error:

I am working on embryos. I cut them in two parts (ICM, wich will become the fetus and TE, which will produce placenta). 
We did RNA seq on 5 embryos/category. I have 2 categories. I performed  a GSEA with GO BP, MF and CC, KEGG and REACTOME databases using Broad Institute software. 

I want to use sumer so I merged gmt files. 
I downloaded gmt with symbol ID from Broad Institue website and then I merged them in one file named mix.gmt
As I am using the same databases between the 2 comparisons, I am using the same gmt file. 
I put this file in a directory which looks like: /path/to/your_work_dir/gmt

I put in a file named ICM_pvalue_file.txt and TE_pvalue_file.txt all pathways/terms and FDR pvalue that are FDR < 0.05 and NES>|2|. 
This file is in the directory: /path/to/your_work_dir/
The file looks like: 

`REACTOME_DEGRADATION_OF_GLI1_BY_THE_PROTEASOME` | 0.000001
-- | --
REACTOME_SCF_SKP2_MEDIATED_DEGRADATION_OF_P27_P21 | 0.000001
REACTOME_NEGATIVE_REGULATION_OF_NOTCH4_SIGNALING | 0.000001
REACTOME_DEGRADATION_OF_AXIN | 0.000001
GO_CYTOPLASMIC_TRANSLATION | 0.0000202
GO_ELECTRON_TRANSPORT_CHAIN | 0.0000211
GO_MITOCHONDRIAL_ELECTRON_TRANSPORT_NADH_TO_UBIQUINONE | 0.0000221
GO_RIBOSOME_ASSEMBLY | 0.0000232
GO_RIBOSOMAL_LARGE_SUBUNIT_BIOGENESIS | 0.0000316
GO_CYTOCHROME_COMPLEX_ASSEMBLY | 0.0000327`

First questions: 

- I am using FDR pvalue as the "score" in this file but I am wondering if NES would not be better. What do you think about it?
- Is a header necessary? I did not use one here. 
- Do I have to transform the FDR pvalue/NES? 

Next I prepared the config file like that:
```
{
  "project":"EPAJ",
  "top_num": 50,
  "similarity": "Jaccard",
  "data": [
    {
      "platform_name":"Inner Cell Mass",
      "platform_abbr":"ICM",
      "gmt_file":"gmt/mix.gmt",
      "score_file":"ICM_pvalue_file.txt"
    },
    {
      "platform_name":"Trophoblast",
      "platform_abbr": "TE",
      "gmt_file":"./gmt/mix.gmt",
      "score_file":"TE_pvalue_file.txt"
    }
    
  ]
}
```
This file name is config_pval.json and is in /path/to/your_work_dir/

I also created a directory for the results: /path/to/your_work_dir/pval_results
Next I opened Rstudio and I did that script: 
```
library(sumer)

setwd("/path/to/your_work_dir/")

sumer("config_pval.json", "./pval_results")
```

And I obtained this error: 

```
> sumer("config_pval.json", "./pval_results")
[1] "platform: Inner Cell Mass"
Error in abs(geneset_info[[cur.set.name]]) : 
  non-numerical argument for a mathematical function

```

When I look in the directory of results, one file named index and another directory has been created. Index just give me the project name. In the directory,  I can find:
- genesets.RData
- topsets.pdf
- topsets.png
- topsets.txt

Could you please help me? 
I do not find when I did a mistake. I think it is in the construction of the files but I do not know where. 

Thank you

Emilie

**Comment by zhiaos** [comment]
Hi Emilie,

Thanks for using the package.

For the score file,  please use the -log(pvalue) or -log(FDR) since by definition of score, larger values are preferable. 

Please also make sure that the score column should contain numeric values only.  I noticed that in your example, the last row contains non-numeric character.  And yes,  the header should also be provided.

Hope this helps,

Zhiao



> Hello
> 
> Thank you for this package, it seems wonderful... but I get an error:
> 
> I am working on embryos. I cut them in two parts (ICM, wich will become the fetus and TE, which will produce placenta).
> We did RNA seq on 5 embryos/category. I have 2 categories. I performed a GSEA with GO BP, MF and CC, KEGG and REACTOME databases using Broad Institute software.
> 
> I want to use sumer so I merged gmt files.
> I downloaded gmt with symbol ID from Broad Institue website and then I merged them in one file named mix.gmt
> As I am using the same databases between the 2 comparisons, I am using the same gmt file.
> I put this file in a directory which looks like: /path/to/your_work_dir/gmt
> 
> I put in a file named ICM_pvalue_file.txt and TE_pvalue_file.txt all pathways/terms and FDR pvalue that are FDR < 0.05 and NES>|2|.
> This file is in the directory: /path/to/your_work_dir/
> The file looks like:
> 
> `REACTOME_DEGRADATION_OF_GLI1_BY_THE_PROTEASOME`	0.000001
> REACTOME_SCF_SKP2_MEDIATED_DEGRADATION_OF_P27_P21	0.000001
> REACTOME_NEGATIVE_REGULATION_OF_NOTCH4_SIGNALING	0.000001
> REACTOME_DEGRADATION_OF_AXIN	0.000001
> GO_CYTOPLASMIC_TRANSLATION	0.0000202
> GO_ELECTRON_TRANSPORT_CHAIN	0.0000211
> GO_MITOCHONDRIAL_ELECTRON_TRANSPORT_NADH_TO_UBIQUINONE	0.0000221
> GO_RIBOSOME_ASSEMBLY	0.0000232
> GO_RIBOSOMAL_LARGE_SUBUNIT_BIOGENESIS	0.0000316
> GO_CYTOCHROME_COMPLEX_ASSEMBLY	0.0000327`
> First questions:
> 
> * I am using FDR pvalue as the "score" in this file but I am wondering if NES would not be better. What do you think about it?
> * Is a header necessary? I did not use one here.
> * Do I have to transform the FDR pvalue/NES?
> 
> Next I prepared the config file like that:
> 
> ```
> {
>   "project":"EPAJ",
>   "top_num": 50,
>   "similarity": "Jaccard",
>   "data": [
>     {
>       "platform_name":"Inner Cell Mass",
>       "platform_abbr":"ICM",
>       "gmt_file":"gmt/mix.gmt",
>       "score_file":"ICM_pvalue_file.txt"
>     },
>     {
>       "platform_name":"Trophoblast",
>       "platform_abbr": "TE",
>       "gmt_file":"./gmt/mix.gmt",
>       "score_file":"TE_pvalue_file.txt"
>     }
>     
>   ]
> }
> ```
> 
> This file name is config_pval.json and is in /path/to/your_work_dir/
> 
> I also created a directory for the results: /path/to/your_work_dir/pval_results
> Next I opened Rstudio and I did that script:
> 
> ```
> library(sumer)
> 
> setwd("/path/to/your_work_dir/")
> 
> sumer("config_pval.json", "./pval_results")
> ```
> 
> And I obtained this error:
> 
> ```
> > sumer("config_pval.json", "./pval_results")
> [1] "platform: Inner Cell Mass"
> Error in abs(geneset_info[[cur.set.name]]) : 
>   non-numerical argument for a mathematical function
> ```
> 
> When I look in the directory of results, one file named index and another directory has been created. Index just give me the project name. In the directory, I can find:
> 
> * genesets.RData
> * topsets.pdf
> * topsets.png
> * topsets.txt
> 
> Could you please help me?
> I do not find when I did a mistake. I think it is in the construction of the files but I do not know where.
> 
> Thank you
> 
> Emilie

Hi Emilie,

Thanks for using the package.

**Comment by ederisoud** [comment]
Hello

thank you for your quick answer. 
I transformed the FDR in -log(FDR) but I still got the same error:
```
> sumer("config_pval.json", "./pval_results")
[1] "platform: Inner Cell Mass"
Error in abs(geneset_info[[cur.set.name]]) : 
  non-numerical argument for a mathematical function
```

I checked my data. The non-numeric character in my example was because of the fomatting of my question. In my data, score column is a numeric variable.
I forgot to mention that I had 0 in some FDR so I replaced them by "0.0000001". 
I also give header : "gene_set" and "score"

Do you have any idea why this error is still hapening? 

Thank you
Emilie

**Comment by ederisoud** [comment]
Hello
Is someone knows where this error is coming from? 

Thank you

Emilie

**Comment by zhiaos** [comment]
Would you mind sharing a portion of your input files and config file?

**Comment by ederisoud** [comment]
Hello

Thank you for your help. 


My config file is:

```
{
  "project":"EPAJ",
  "top_num": 50,
  "similarity": "Jaccard",
  "data": [
    {
      "platform_name":"Inner Cell Mass",
      "platform_abbr":"ICM",
      "gmt_file":"gmt/mix.gmt",
      "score_file":"ICM_pvalue_file.txt"
    },
    {
      "platform_name":"Trophoblast",
      "platform_abbr": "TE",
      "gmt_file":"./gmt/mix.gmt",
      "score_file":"TE_pvalue_file.txt"
    }
    
  ]
}
```

My gmt_file is a merged file with gmt from MSigDB (KEGG, GO BP, GO MF, GO CC and REACTOME). I downloaded it on this wetransfer at this lik as it is too big for github: https://we.tl/t-w3YaKoG2GF

My score file is :
[ICM_pvalue_file.txt](https://github.com/bzhanglab/sumer/files/5109305/ICM_pvalue_file.txt)

I have two files as the one I am sharing (One for TE and another one for ICM)

My R script is very simple:

library(sumer)

setwd("/path/to/my_work_dir/")


sumer("config_pval.json", "./pval_results")


Thank you 

Emilie

**Comment by zhiaos** [comment]
Looks like your GMT file has empty fields on each row.  Can you remove them first?

**Comment by ederisoud** [comment]
Hello

Thank you for your answer. 

I did not notice that. I think it is because to find a solution I opened and saved it in Excel. 
So I concatenated gmt form Broad Institute again and I obtained the file at this link: https://we.tl/t-X2xQzg3FyY
I retry with this new gmt file and I am still getting the same error. 
I also tried to replace the description (here the website link) by just the name of the pathway and I am still getting the same error. 

I'm running out of ideas...

Thank you for your help

Emilie

**Comment by apuhegde** [comment]
Hello! I am also facing this issue. I double checked that the score values  in my input files have no non-numeric characters as well as transformed to be -log(pVal) values. My gmt also has no NA or empty fields in any of the columns. I still get the same error:

```
Error in abs(geneset_info[[cur.set.name]]) : 
  non-numeric argument to mathematical function
```

Has this issue been resolved yet? Thanks!

**Comment by ederisoud** [comment]
Hello

I have left this analysis aside for the moment because the authors and I didn't find a solution last time... 

Emilie

**Comment by medibuntu** [comment]
Hi,

any updates in the meantime? Been trying to run an analysis with sumer and I get the same error as previously reported. I use an untouched *.gmt file from the Broad as well as a very simple score file with tab separated pathways and -log(FDR) scores. 
No empty rows whatsoever. 

Still, error with abs(geneset_info[[cur.set.name]])

I tried to reproduce the error by manually loading the geneset_info from my score_file.txt which works fine (using lines 61-64 from sumer.R); it creates a named list object (the GO Term being the element name and the value being the -log(p.adj)) and I can subset every object of the list by it's name and use it as input for abs()

```
score_list <- scan("protein_C1_enrichment.txt", what="", sep="\n", quiet=TRUE) # this works
score_list <- strsplit(score_list, "\t") # this works
names(score_list) <- sapply(score_list, `[[`, 1) # this works
geneset_info <- lapply(score_list, `[`, c(-1)) # this works
geneset_info <- lapply(geneset_info, "as.double") #this works
abs(geneset_info[["HP_ABNORMALITY_OF_THE_VASCULATURE_OF_THE_EYE"]]) # this gives me the double value for my -log(p)
```
So apparently somewhere along the way this gets messed up when used inside marginalGain()

Thanks!

**Comment by zhiaos** [comment]
Hi,

Can you please share the genesets.RData files which were saved in the output directory (under each subdirectory with UUID names)?

Thanks,
Zhiao

> Hi,
> 
> any updates in the meantime? Been trying to run an analysis with sumer and I get the same error as previously reported. I use an untouched *.gmt file from the Broad as well as a very simple score file with tab separated pathways and -log(FDR) scores.
> No empty rows whatsoever.
> 
> Still, error with abs(geneset_info[[cur.set.name]])
> 
> I tried to reproduce the error by manually loading the geneset_info from my score_file.txt which works fine (using lines 61-64 from sumer.R); it creates a named list object (the GO Term being the element name and the value being the -log(p.adj)) and I can subset every object of the list by it's name and use it as input for abs()
> 
> ```
> score_list <- scan("protein_C1_enrichment.txt", what="", sep="\n", quiet=TRUE) # this works
> score_list <- strsplit(score_list, "\t") # this works
> names(score_list) <- sapply(score_list, `[[`, 1) # this works
> geneset_info <- lapply(score_list, `[`, c(-1)) # this works
> geneset_info <- lapply(geneset_info, "as.double") #this works
> abs(geneset_info[["HP_ABNORMALITY_OF_THE_VASCULATURE_OF_THE_EYE"]]) # this gives me the double value for my -log(p)
> ```
> 
> So apparently somewhere along the way this gets messed up when used inside marginalGain()
> 
> Thanks!

**Comment by medibuntu** [comment]
Please find it here
https://we.tl/t-0ttcvv48Z9

looks good to me. 

Thank you for your support!

Best

**Comment by zhiaos** [comment]
Thanks. Is this the only file you have?

> Please find it here
> https://we.tl/t-0ttcvv48Z9
> 
> looks good to me.
> 
> Thank you for your support!
> 
> Best

**Comment by medibuntu** [comment]
The folder contains this RData file along with the pdf, png and text file representation of the ranked genesets (the topset files). That's all

**Comment by zhiaos** [comment]
I mean how many platforms do you have?

**Comment by medibuntu** [comment]
Currently only proteomics and my goal is to use sumer for pathway consolidation here

**Comment by zhiaos** [comment]
can you try the latest release?

**Comment by medibuntu** [comment]
Thanks, but I still get the error! 

Again, in the RData file I can subset the genset_info by it's name so it's either the definition of curr.gene.set or maybe you try to index outside the genset_info list?

btw I updated all my libraries/R to make sure that's not the isse...

**Comment by zhiaos** [comment]
can you share the config file, gmt file and score file?

**Comment by medibuntu** [comment]
Happy to
https://we.tl/t-LqeUwMo2Jb

**Comment by zhiaos** [comment]
Can you try with the latest update?  It worked for me with your input files.

**Comment by medibuntu** [comment]
I tried, actually re-installed the package several times (via devtools)  throughout the day. Still not working. I also tried running it with a native R Gui and not in RStudio, still not working. Maybe it's the OS? I'm running Windows. 

Here's my session info, in case you're wondering

R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
[3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sumer_1.1.5

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6       magrittr_2.0.1   uuid_0.1-4       tidyselect_1.1.0
 [5] munsell_0.5.0    colorspace_2.0-0 lattice_0.20-41  R6_2.5.0        
 [9] rlang_0.4.10     dplyr_1.0.3      tools_4.0.3      parallel_4.0.3  
[13] grid_4.0.3       gtable_0.3.0     DBI_1.1.1        ellipsis_0.3.1  
[17] digest_0.6.27    assertthat_0.2.1 tibble_3.0.5     lifecycle_0.2.0 
[21] crayon_1.3.4     Matrix_1.3-2     farver_2.0.3     purrr_0.3.4     
[25] apcluster_1.4.8  ggplot2_3.3.3    vctrs_0.3.6      glue_1.4.2      
[29] proxy_0.4-24     compiler_4.0.3   pillar_1.4.7     generics_0.1.0  
[33] scales_1.1.1     jsonlite_1.7.2   pkgconfig_2.0.3 
>

**Comment by zhiaos** [comment]
Not exactly sure. The results I got is here {link}
You still get the same error message?

**Comment by medibuntu** [comment]
Yes, still 

Error in abs(geneset_info[[cur.set.name]]) : 
  non-numerical argument for a mathematical function

I also made sure that abs() is not masked by any other library. 
Strainge issue...
Thanks for sharing, however, it's restricted access!

**Comment by zhiaos** [comment]
link removed.  That's strange. My environment:

R version 4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(sumer)
> sumer("configfile_c1.json", "xxxx")
[1] "platform: Proteomics"
[1] "ending weighted set cover"
Saving 7 x 7 in image
Saving 7 x 7 in image
  adding: ap_sumer_nodelist.txt (deflated 59%)
  adding: ap_sumer_edgelist.txt (deflated 77%)
  adding: ap_sumer.json (deflated 83%)
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux bullseye/sid

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.13.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] sumer_1.1.5

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6       magrittr_2.0.1   tidyselect_1.1.0 munsell_0.5.0
 [5] uuid_0.1-4       colorspace_2.0-0 lattice_0.20-41  R6_2.5.0
 [9] rlang_0.4.10     dplyr_1.0.3      tools_4.0.3      parallel_4.0.3
[13] grid_4.0.3       gtable_0.3.0     withr_2.4.0      ellipsis_0.3.1
[17] digest_0.6.27    tibble_3.0.5     lifecycle_0.2.0  crayon_1.3.4
[21] Matrix_1.3-2     farver_2.0.3     purrr_0.3.4      apcluster_1.4.8
[25] ggplot2_3.3.3    vctrs_0.3.6      glue_1.4.2       labeling_0.4.2
[29] proxy_0.4-24     compiler_4.0.3   pillar_1.4.7     generics_0.1.0
[33] scales_1.1.1     jsonlite_1.7.2   pkgconfig_2.0.3

**Comment by medibuntu** [comment]
I didn't mean that you can't share the results but instead that i'm not able to see it because your cloud storage is restricted access ;-) I'd be interested to see the results you obtained!

I'll try to run the code on a different machine, e.g. a linux vpn. This has to be an OS issue..

**Comment by zhiaos** [comment]
Here is the link: {link}
Please let me know after you download it so that I can remove it.

**Comment by medibuntu** [comment]
Got it, thanks! And your algorithm is indeed very helpful. It's a pitty that this puzzling issue remains. Fingers crossed that you guys will figure this out!

**Comment by zhiaos** [comment]
BTW, for single omics analysis, you can also use http://www.webgestalt.org, the algorithm here is built into the web app.

**Comment by ederisoud** [comment]
Hello

Did you figure out what is the problem? 

For my part, I can't download the last uptade. 
This error message appears:
```
> devtools::install_github("bzhanglab/sumer")
Downloading GitHub repo bzhanglab/sumer@HEAD
√  checking for file 'C:\Users\ederisoud\AppData\Local\Temp\RtmpQPkWQs\remotes416055aa1514\bzhanglab-sumer-bc8fe68/DESCRIPTION' ...
-  preparing 'sumer':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'sumer_1.1.5.tar.gz'
```
   
```
Installing package into ‘C:/Users/ederisoud/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package 'sumer' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'sumer'
    finding HTML links ... fini
    affinityPropagation                     html  
    sumer                                   html  
    topGeneSets                             html  
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
*** arch - i386
Error: package or namespace load failed for 'sumer' in library.dynam(lib, package, package.lib):
 DLL 'jsonlite' not found: maybe not installed for this architecture?
Erreur : le chargement a échoué
Exécution arrêtée
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Users/ederisoud/Documents/R/win-library/4.0/sumer'
* restoring previous 'C:/Users/ederisoud/Documents/R/win-library/4.0/sumer'
Erreur : Failed to install 'sumer' from GitHub:
  (converti depuis l'avis) installation of package ‘C:/Users/EDERIS~1/AppData/Local/Temp/RtmpQPkWQs/file4160662f2357/sumer_1.1.5.tar.gz’ had non-zero exit status
```

Thank you

Emilie

**Comment by medibuntu** [comment]
DLL 'jsonlite' not found: maybe not installed for this architecture?

I'd suggest reinstalling this first

https://www.rdocumentation.org/packages/jsonlite/versions/1.7.2

However, sumer still won't run on my machine..

**Comment by ederisoud** [comment]
Oh Yes !
I did not see the error link to jsonlite. Thank you!
I succeed to install the new update of SUMER. However, I still got the exactly same error message too. 

Emilie

**Comment by ederisoud** [comment]
Well, I tried to run line by line the function and I got the same kind of error when I am loading the config_file (So I am lock at the first row as we need it after). 

I think the issue is with this file, when it is loading. 

As I do not understand very well the function check_config, I could not find where is the issue. 

Emilie

**Comment by zhiaos** [comment]
can you share the config file?

> Well, I tried to run line by line the function and I got the same kind of error when I am loading the config_file (So I am lock at the first row as we need it after).
> 
> I think the issue is with this file, when it is loading.
> 
> As I do not understand very well the function check_config, I could not find where is the issue.
> 
> Emilie

**Comment by ederisoud** [comment]
Hello

The config file I used is shared above in the conversation.

Emilie

**Comment by zhiaos** [comment]
can you re-upload all the input files?  The link seems to be expired.

**Comment by ederisoud** [comment]
Please find all my data here:
https://filesender.renater.fr/?s=download&token=79d97947-3f35-48d2-9aee-68f61c6b02c2

Emilie

**Comment by zhiaos** [comment]
I worked for me.  I've uploaded the results here: https://drive.google.com/file/d/1BEjY28z_3V7PWJmHy1NqSE8ogsFlxd36/view?usp=sharing 

I've tested both on MacOS and Linux.  However I don't have access to a Windows machine right now.  Will look into it later.

**Comment by ederisoud** [comment]
Thank you but I have a lot of data to analyze and that is just one part. I can't just ask you everytime I need an analyze. Please let us know if you find out where is the problem. 

Thank you

Emilie

**Comment by zhiaos** [comment]
In the meantime, do you have access to mac or linux machine to test?

**Comment by ederisoud** [comment]
Hello
I can have access to mac on monday. I will let you know. 

Emilie

**Comment by ederisoud** [comment]
Dear all

I tried on Mac system and SUMER worked very well. The issue is therefore linked to windows system. Could you correct this issue in the next update ? because, on my side, I do not have access to a mac easily. 

Thank you

Emilie
