### ISSUE TITLE
Cannot xtfrm data frames

### ISSUE THREAD

**Issue by IzacFindlay** [bzhanglab/sumer#6]
Hi.

This is perhaps a simple error, but I am relatively new to R.

When trying the run the example dataset/code, I continually get the error:

> sumer("config.json", "results")
[1] "platform: proteomics"
Error in xtfrm.data.frame(x) : cannot xtfrm data frames

I am not editing the sample data or code in any way. If anyone can help, it would be greatly appreciated.

Thanks.

**Comment by zhiaos** [comment]
Hi, 

Thanks for reporting the error.  An issue has been identified and fixed. Please reinstall the package and try again.
